from __future__ import annotations

from cyndilib.audio_frame import AudioFrameSync
from cyndilib.video_frame import VideoFrameSync
from cyndilib.wrapper import *


class BaseFrameSyncHelper:

    def __cinit__(self, *args, **kwargs):
        ...

    @property
    def num_allocs(self):
        """Number of frames sent"""

    @property
    def num_frees(self):
        """Number of frames freed by the audio frame"""

    @property
    def num_outstanding(self):
        """Number of frames that were sent but not freed yet"""

class AudioFrameSyncHelper(BaseFrameSyncHelper):

    def set_audio_frame(self, audio_frame: AudioFrameSync):
        ...

    def fill_data(self, samples: memoryview, sample_rate: int, timestamp: float):
        """Fill audio frame with data and simulate the processing that
        occurs within the `FrameSync` and `AudioFrameSync` classes.
        """

    def free_previous(self):
        """Free the previously allocated audio frame, if any"""

class VideoFrameSyncHelper(BaseFrameSyncHelper):

    def __cinit__(self, *args, **kwargs):
        ...

    def __init__(self, *args, **kwargs):
        ...

    def __dealloc__(self):
        ...

    def set_video_frame(self, video_frame: VideoFrameSync):
        ...

    def fill_data(self, arr: memoryview, width: int, height: int, timestamp: float):
        """Fill video frame with data and simulate the processing that
        occurs within the `FrameSync` and `VideoFrameSync` classes.
        """

    def free_previous(self):
        """Free the previously allocated video frame, if any"""

# This file was generated by stubgen-pyx v0.2.2 from _framesync_helpers.pyx