from __future__ import annotations

from cyndilib.wrapper.common import *


class InvalidExceptionType(TypeError):
    ...

def raise_py_exc(exc_type: object, msg: str='1234'):
    ...

# This file was generated by stubgen-pyx v0.2.2 from _test_exceptions.pyx