from __future__ import annotations

from cyndilib.audio_frame import AudioSendFrame
from cyndilib.send_frame_status import *
from cyndilib.video_frame import VideoSendFrame
from cyndilib.wrapper import *


def get_max_frame_buffers():
    ...

def get_null_idx():
    ...

def set_send_frame_sender_status(frame: object, attached: bool):
    ...

def set_send_frame_send_complete(frame: object):
    ...

def write_audio_frame_memview(af: AudioSendFrame, data: memoryview):
    ...

def get_audio_frame_data(af: AudioSendFrame, dest_arr: memoryview):
    ...

def get_video_frame_data(vf: VideoSendFrame, dest_arr: memoryview):
    ...

def check_audio_send_frame(af: AudioSendFrame, write_index=None, read_index=None):
    ...

def check_video_send_frame(vf: VideoSendFrame, write_index=None, read_index=None):
    ...

def assert_equal(a, b, msg=''):
    ...

def assert_not_equal(a, b, msg=''):
    ...

def assert_in_range(a, vmin, vmax, msg=''):
    ...

def test_indexing():
    ...

# This file was generated by stubgen-pyx v0.2.2 from _test_send_frame_status.pyx
