from __future__ import annotations

import cython
import numpy as np
from cyndilib.video_frame import VideoRecvFrame
from cyndilib.wrapper import *

RGBA_dtype = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)], align=True)

def build_test_frame(width: int, height: int, as_uint32: bool=True, as_flat_uint8: bool=False, as_structured: bool=False, x_offset: int=0):
    ...

def build_test_frames(width: int, height: int, num_frames: int, as_uint32: bool=True, as_flat_uint8: bool=False, as_structured: bool=False):
    ...

@cython.boundscheck(False)
@cython.wraparound(False)
def buffer_into_video_frame(vf: VideoRecvFrame, width: int, height: int, arr: memoryview, do_process: bool=True):
    ...

def video_frame_process_events(vf: VideoRecvFrame):
    ...

# This file was generated by stubgen-pyx v0.2.2 from _test_video_frame.pyx