from __future__ import annotations

from cyndilib.audio_frame import AudioFrameSync, AudioRecvFrame, AudioSendFrame
from cyndilib.wrapper import *


def get_audio_send_frame_current_data(audio_frame: AudioSendFrame):
    """Hook to read the data from an AudioSendFrame directly after
    writing to it, but before it's been sent.
    """

def audio_frame_process_events(audio_frame: AudioRecvFrame):
    ...

def fill_audio_frame(audio_frame: AudioRecvFrame, samples: memoryview, sample_rate: int, timestamp: float, do_process: bool=True, check_can_receive: bool=False):
    ...

def fill_audio_frame_sync(audio_frame: AudioFrameSync, samples: memoryview, sample_rate: int, timestamp: float, do_process: bool=True):
    ...

# This file was generated by stubgen-pyx v0.2.2 from _test_audio_frame.pyx