from __future__ import annotations

import cython
import numpy as np
import numpy.typing as npt
from cyndilib.sender import Sender
from cyndilib.wrapper import *


@cython.boundscheck(False)
@cython.wraparound(False)
def test_send_video_and_audio(sender: Sender, fake_frames: memoryview|npt.NDArray[np.uint8], audio_samples: memoryview|npt.NDArray[np.float32], frame_rate: object, num_frame_repeats: int=10, num_full_repeats: int=1, send_audio: bool=True):
    ...

# This file was generated by stubgen-pyx v0.2.2 from _test_sender.pyx
