name: Codspeed

on:
  push:
    branches: [main]
    paths:
      - "pyproject.toml"
      - "setup.py"
      - "setup.cfg"
      - "src/**"
      - "tests/**"
      - ".github/workflows/codspeed.yml"
      - "uv.lock"
  pull_request:
    branches: [main]
    paths:
      - "pyproject.toml"
      - "setup.py"
      - "setup.cfg"
      - "src/**"
      - "tests/**"
      - ".github/workflows/codspeed.yml"
      - "uv.lock"

  workflow_dispatch:

jobs:
  benchmark:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: "3.13"

      - name: Install Project
        run: uv sync --frozen --group test
        env:
          CYNDILIB_BUILD_PARALLEL: auto

      - name: Compile tests
        run: uv run python build_tests.py

      - name: Run benchmarks
        uses: CodSpeedHQ/action@4296e51e7041e24dadb86d1d6e8b9320d223dbe8 # v5
        with:
          mode: simulation
          run: uv run py.test tests/ --codspeed -n=0
