name: Codspeed

on:
  push:
    branches: [main]
    paths:
      - "pyproject.toml"
      - "setup.py"
      - "setup.cfg"
      - "src/**"
      - "tests/**"
      - ".github/workflows/codspeed.yml"
  pull_request:
    branches: [main]
    paths:
      - "pyproject.toml"
      - "setup.py"
      - "setup.cfg"
      - "src/**"
      - "tests/**"
      - ".github/workflows/codspeed.yml"

  workflow_dispatch:

jobs:
  benchmark:
    runs-on: codspeed-macro
    strategy:
      fail-fast: false
      matrix:
        instrumentation-mode: [simulation, walltime]
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Project
        run: uv sync --frozen --group test
        env:
          CYNDILIB_BUILD_PARALLEL: auto

      - name: Compile tests
        run: uv run python build_tests.py

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: ${{ matrix.instrumentation-mode }}
          run: uv run py.test tests/ --codspeed -n=0
